//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PJCMobile
{
    using System;
    using System.Collections.Generic;
    
    public partial class prompttype
    {
        public prompttype()
        {
            this.prompts = new HashSet<prompt>();
        }
    
        public int typeID { get; set; }
        public string typeName { get; set; }
    
        public virtual ICollection<prompt> prompts { get; set; }
    }
}
