//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PJCMobile
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.usertasks = new HashSet<usertask>();
            this.usertaskprompts = new HashSet<usertaskprompt>();
            this.jobs = new HashSet<job>();
            this.Users1 = new HashSet<User>();
            this.Users = new HashSet<User>();
            this.Roles = new HashSet<Role>();
        }
    
        public System.Guid UserId { get; set; }
        public System.Guid ApplicationId { get; set; }
        public string UserName { get; set; }
        public bool IsAnonymous { get; set; }
        public System.DateTime LastActivityDate { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual Membership Membership { get; set; }
        public virtual Profile Profile { get; set; }
        public virtual ICollection<usertask> usertasks { get; set; }
        public virtual ICollection<usertaskprompt> usertaskprompts { get; set; }
        public virtual ICollection<job> jobs { get; set; }
        public virtual ICollection<User> Users1 { get; set; }
        public virtual ICollection<User> Users { get; set; }
        public virtual ICollection<Role> Roles { get; set; }
    }
}
