//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PJCAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuthToken
    {
        public int authTokenID { get; set; }
        public string userName { get; set; }
        public string token { get; set; }
        public System.DateTime expirationDate { get; set; }
    
        public virtual UserName UserName1 { get; set; }
    }
}
