//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PJCAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailOutbox
    {
        public int emailOutboxID { get; set; }
        public string emailAddress { get; set; }
        public string emailName { get; set; }
        public string emailPassword { get; set; }
        public string smtpServerName { get; set; }
        public int portNumber { get; set; }
        public int smtpTimeout { get; set; }
        public string purpose { get; set; }
    }
}
