//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PJCAdmin.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
    [DataContract]
    public partial class Feedback
    {
        public Feedback()
        {
            this.Routines = new HashSet<Routine>();
            this.Tasks = new HashSet<Task>();
        }
    
        [IgnoreDataMember]
        public int feedbackID { get; set; }
        [IgnoreDataMember]
        public byte mediaTypeID { get; set; }
        [IgnoreDataMember]
        public byte feedbackTypeID { get; set; }
        [DataMember]
        public string feedbackTitle { get; set; }
        [DataMember]
        public string feedbackMessage { get; set; }
    
        [DataMember]
        public virtual FeedbackType FeedbackType { get; set; }
        [DataMember]
        public virtual MediaType MediaType { get; set; }
        [IgnoreDataMember]
        public virtual ICollection<Routine> Routines { get; set; }
        [IgnoreDataMember]
        public virtual ICollection<Task> Tasks { get; set; }
    }
}
