//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PJCAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        public Job()
        {
            this.Steps = new HashSet<Step>();
            this.Notes = new HashSet<Note>();
        }
    
        public int jobID { get; set; }
        public int routineID { get; set; }
        public System.DateTime startTime { get; set; }
    
        public virtual Routine Routine { get; set; }
        public virtual ICollection<Step> Steps { get; set; }
        public virtual ICollection<Note> Notes { get; set; }
    }
}
