//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PJCAdmin.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]
    public partial class MediaType
    {
        public MediaType()
        {
            this.Feedbacks = new HashSet<Feedback>();
        }
    
        [IgnoreDataMember]
        public byte mediaTypeID { get; set; }
        [DataMember]
        public string mediaTypeName { get; set; }
    
        [IgnoreDataMember]
        public virtual ICollection<Feedback> Feedbacks { get; set; }
    }
}
