//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PJCAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageType
    {
        public MessageType()
        {
            this.Routines = new HashSet<Routine>();
            this.Routines1 = new HashSet<Routine>();
            this.Tasks = new HashSet<Task>();
            this.Tasks1 = new HashSet<Task>();
            this.Tasks2 = new HashSet<Task>();
        }
    
        public byte messageTypeID { get; set; }
        public string messageTypeName { get; set; }
    
        public virtual ICollection<Routine> Routines { get; set; }
        public virtual ICollection<Routine> Routines1 { get; set; }
        public virtual ICollection<Task> Tasks { get; set; }
        public virtual ICollection<Task> Tasks1 { get; set; }
        public virtual ICollection<Task> Tasks2 { get; set; }
    }
}
