//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PJCAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Note
    {
        public Note()
        {
            this.Jobs = new HashSet<Job>();
            this.Steps = new HashSet<Step>();
            this.UserNames = new HashSet<UserName>();
        }
    
        public int noteID { get; set; }
        public string noteTitle { get; set; }
        public string noteMessage { get; set; }
    
        public virtual ICollection<Job> Jobs { get; set; }
        public virtual ICollection<Step> Steps { get; set; }
        public virtual ICollection<UserName> UserNames { get; set; }
    }
}
