//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PJCAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Note
    {
        public int noteID { get; set; }
        public int jobID { get; set; }
        public int routineID { get; set; }
        public Nullable<byte> stepNo { get; set; }
        public string noteTitle { get; set; }
        public string noteMessage { get; set; }
    
        public virtual Job Job { get; set; }
    }
}
