//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PJCAdmin.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
    [DataContract]
    public partial class Routine
    {
        public Routine()
        {
            this.Jobs = new HashSet<Job>();
            this.Tasks = new HashSet<Task>();
            this.Feedbacks = new HashSet<Feedback>();
        }
    
        [IgnoreDataMember]
        public int routineID { get; set; }
        [DataMember]
        public string creatorUserName { get; set; }
        [DataMember]
        public string assigneeUserName { get; set; }
        [DataMember]
        public string routineTitle { get; set; }
        [DataMember]
        public bool isTimed { get; set; }
        [DataMember]
        public Nullable<System.TimeSpan> expectedDuration { get; set; }
        [DataMember]
        public bool isNotifiable { get; set; }
        [IgnoreDataMember]
        public System.DateTime updatedDate { get; set; }
        [IgnoreDataMember]
        public bool isDisabled { get; set; }
    
        [IgnoreDataMember]
        public virtual ICollection<Job> Jobs { get; set; }
        [IgnoreDataMember]
        public virtual UserName UserName { get; set; }
        [IgnoreDataMember]
        public virtual UserName UserName1 { get; set; }
        [DataMember]
        public virtual ICollection<Task> Tasks { get; set; }
        [DataMember]
        public virtual ICollection<Feedback> Feedbacks { get; set; }
    }
}
