//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PJCAdmin.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
    [DataContract]
    public partial class Task
    {
        public Task()
        {
            this.Feedbacks = new HashSet<Feedback>();
        }
    
        [IgnoreDataMember]
        public int routineID { get; set; }
        [DataMember]
        public byte sequenceNo { get; set; }
        [IgnoreDataMember]
        public byte taskCategoryID { get; set; }
        [DataMember]
        public string taskName { get; set; }
        [DataMember]
        public string taskDescription { get; set; }
        [DataMember]
        public bool isTimed { get; set; }
        [DataMember]
        public Nullable<System.TimeSpan> expectedDuration { get; set; }
        [IgnoreDataMember]
        public int taskID { get; set; }
    
        [IgnoreDataMember]
        public virtual Routine Routine { get; set; }
        [DataMember]
        public virtual TaskCategory TaskCategory { get; set; }
        [DataMember]
        public virtual ICollection<Feedback> Feedbacks { get; set; }
    }
}
