//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PJCAdmin.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class taskcategory
    {
        public taskcategory()
        {
            this.tasks = new HashSet<task>();
        }

        [DisplayName("Category ID")]
        public int categoryID { get; set; }
        [DisplayName("Category Name")]
        public string categoryName { get; set; }

        public virtual ICollection<task> tasks { get; set; }
    }
}
