//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PJCAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserName
    {
        public UserName()
        {
            this.AuthTests = new HashSet<AuthTest>();
            this.AuthTokens = new HashSet<AuthToken>();
        }
    
        public string UserName1 { get; set; }
        public System.Guid UserID { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<AuthTest> AuthTests { get; set; }
        public virtual ICollection<AuthToken> AuthTokens { get; set; }
    }
}
