//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PJCAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserName
    {
        public UserName()
        {
            this.AuthTests = new HashSet<AuthTest>();
            this.AuthTokens = new HashSet<AuthToken>();
            this.UserName11 = new HashSet<UserName>();
            this.UserName12 = new HashSet<UserName>();
            this.Routines = new HashSet<Routine>();
            this.Routines1 = new HashSet<Routine>();
            this.Notes = new HashSet<Note>();
        }
    
        public string userName1 { get; set; }
        public System.Guid userID { get; set; }
        public string jobCoachUserName { get; set; }
        public string guardianUserName { get; set; }
    
        public virtual ICollection<AuthTest> AuthTests { get; set; }
        public virtual ICollection<AuthToken> AuthTokens { get; set; }
        public virtual ICollection<UserName> UserName11 { get; set; }
        public virtual UserName UserName2 { get; set; }
        public virtual ICollection<UserName> UserName12 { get; set; }
        public virtual UserName UserName3 { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<Routine> Routines { get; set; }
        public virtual ICollection<Routine> Routines1 { get; set; }
        public virtual ICollection<Note> Notes { get; set; }
    }
}
