//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PJCAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usertaskprompt
    {
        public int userID { get; set; }
        public int taskID { get; set; }
        public int promptID { get; set; }
        public Nullable<int> promptLengthMin { get; set; }
    
        public virtual prompt prompt { get; set; }
        public virtual task task { get; set; }
        public virtual user user { get; set; }
    }
}
